### ISSUE TITLE
[BUG] RPC dont work

### ISSUE THREAD

**Issue by GamerClassN7** [Lachee/discord-rpc-csharp#107]
**Describe the bug**
RPC not showing 

**To Reproduce**
my code is down below
`using DiscordRPC;
using DiscordRPC.Logging;
using System;

namespace DIscord
{

    class Program
    {
        static void Main(string[] args)
        {

			DiscordRpcClient client = new DiscordRpcClient("");
	
			client.Logger = new ConsoleLogger() { Level = LogLevel.Warning };

			client.OnReady += (sender, e) =>
			{
				Console.WriteLine("Received Ready from user {0}", e.User.Username);
			};

			client.OnPresenceUpdate += (sender, e) =>
			{
				Console.WriteLine("Received Update! {0}", e.Presence);
			};

			client.Initialize();
			while (true)
            {
				if (client.IsInitialized) Console.WriteLine("test");
				client.SetPresence(new RichPresence()
				{
					Details = "Example Project",
					State = "csharp example",
					Assets = new Assets()
				});
			}
			Console.ReadKey();
			Console.WriteLine("Hello World!");
        }
    }
}
`

**Expected behavior**
show RPC

**Desktop (please complete the following information):**
 - OS: Window
 - Framework: 4
 - Version: last

can ani body suggest what i am doing wrong ?

**Comment by Lachee** [comment]
Client ID is missing. Also make sure you have Game Activity enabled in your discord settings
![img](https://i.lu.je/2020/Discord_3GvUW17WU5.png)

**Comment by GamerClassN7** [comment]
Thank you! It is working perfectly now 👍
