### ISSUE TITLE
[BUG] Timestamps text

### ISSUE THREAD

**Issue by AbdShullah** [Lachee/discord-rpc-csharp#111]
**Describe the bug**
The presence text is weird:
Remaining text for one minute20:27

**To Reproduce**
1. Use Timestamps with End

**Expected behavior**
Correct behavior:
20:27 left

![unknown](https://user-images.githubusercontent.com/43544435/104911249-dba03280-598a-11eb-93ce-9fea11558d1a.png)
("Pozostało" means "remaining" in my language)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win 10
 - Framework: 5
 - Version: [e.g. 0.202] 1.0169

**Comment by Lachee** [comment]
Does this happen only in your locale? This is likely a Discord bug and I won't be able to fix it.
If it is only in your language, try bringing it up with https://discord.gg/discord-testers as it is a translation error in Discord itself.

**Comment by AbdShullah** [comment]
It actually was problem with my discord client, I switched to english then to my language and it works propely now.
