### ISSUE TITLE
[FEATURE REQUEST] Buttons

### ISSUE THREAD

**Issue by Dultus** [Lachee/discord-rpc-csharp#112]
Hello,
I'd just like to request the new button feature Discord added in a month back.
The JS Discord API supports it already. Sadly not the C# one:

https://i.imgur.com/zucURBI.png

Best Regards

**Comment by Lachee** [comment]
This is a work in progress. I am planning to add this feature but its currently unsuitable with how this library works and isn't officially documented.

> Just double checked the REST endpoint as well and it mirrors, but I agree that it's weird. Custom buttons are not a "full feature" yet so I'm not sure if we'll prioritize changing this API anytime soon but I've noted it on a ticket. The only folks using it right now are doing so via HTTP so changing the response for them wouldn't be a problem
https://discord.com/channels/613425648685547541/697489244649816084/796887257570213978

**Comment by fenwikk** [comment]
#114

**Comment by Lachee** [comment]
> #114

oh you are right. I completely forgot about this issue. 
Thanks!

**Comment by Mrgaton** [comment]
ee

**Comment by Mrgaton** [comment]
How i canuse buttons
