### ISSUE TITLE
[BUG] error CS1503 in Unity

### ISSUE THREAD

**Issue by fenwikk** [Lachee/discord-rpc-csharp#115]
**Describe the bug**
Assets\Discord RPC\Example\Rich Presence\Example_RichPresence.cs(36,38): error CS1503: Argument 1: cannot convert from 'DiscordRPC.BaseRichPresence' to 'DiscordRPC.RichPresence'

**To Reproduce**
1. Download UnityPackage
2. Import UnityPackage
3. See error

**Expected behavior**
No error should appear

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Latest from Artifacts

**Additional context**

**Comment by Lachee** [comment]
Thanks for the report. Forgot to update the unity package. I'll work on this.

**Comment by Lachee** [comment]
This has been resolved
