### ISSUE TITLE
[BUG] Asynchronous calls

### ISSUE THREAD

**Issue by HeberonYT** [Lachee/discord-rpc-csharp#122]
Hi, I have a query, are the calls running asynchronously?
Should I make the calls in a sub process so as not to freeze the application during the request?

Nice work with the API, thanks.

**Comment by Lachee** [comment]
All the calls are queued to a thread, which sends them to discord in the background. 
You dont need to worry about sub-processes, since it technically is one already. 
Please note

**Comment by HeberonYT** [comment]
Thanks for the info.
If calls are already in the background, then everything is fine for me. Thanks a lot.
