### ISSUE TITLE
[BUG] Button is not opening URL

### ISSUE THREAD

**Issue by mady005** [Lachee/discord-rpc-csharp#124]
I added a button like this
`presence.Buttons = new Button[]
                            {
                    new Button() { Label = "Best song", Url = "https://www.youtube.com/watch?v=yoZy2E17-50" }
                            };`
But for some reason when I'm clicking the button it's not opening the URL

**Comment by Lachee** [comment]
> I added a button like this
> `presence.Buttons = new Button[] { new Button() { Label = "Best song", Url = "https://www.youtube.com/watch?v=yoZy2E17-50" } };`
> But for some reason when I'm clicking the button it's not opening the URL

Pretty sure this is a discord bug, you cannot click on your own links.
