### ISSUE TITLE
Add Linux / Mac Support

### ISSUE THREAD

**Issue by Lachee** [Lachee/discord-rpc-csharp#13]
The library currently only supports Windows machines. This is mostly due to the Uri Scheme registration working with only Windows registry (I am unsure how it translates between OS) and the native pipe recently created uses only the windows api (this is only for Unity projects, the standard pipe client uses C# managed system which should be cross platform).

**Comment by bigworld12** [comment]
i suggest moving the library to .net standard 2.0 this will automatically open support to all platforms
i will create a branch and try to migrate the library

**Comment by Lachee** [comment]
A new branch for .NET Standard would be appropriate, but that does not solve the platform compatibility issues and in fact makes it worse. This project is using .NET 3.5 for compatibility with the Unity3D 5 game engine. While this is a older version of unity now, it is still used by many games. Moving to .NET Standard would result in losing this support as only late Unity 2017 (because of poor implementation in early versions) and Unity 2018 games would work.

The core issue here isn't the .NET framework used either. Just because its .NET 3.5, you are not prevented from using it in a .NET Standard project. The reason its not compatible with Linux or MacOS is because of 2 issues:
A) Native Pipes. This project uses Native Pipes as a work around for the Unity3D shotty implementation of ManagedNamedPipes. Unity3D cannot handle proper ManagedNamedPipes and a native wrapper has to be utilised. (In normal projects outside of Unity3D this is not required). The native wrapper this project is using has currently only been written for windows. A port to Unix NamedPipes would be required. While not hard, I just not have had the time to do so yet (my C++ isn't the strongest either).

B) URI Scheme Implementation. The offical Discord RPC library faced this issue too. There are 3 different ways of registering a new Uri Scheme for the 3 operating systems. Windows has been completed with a simple registry edit, however linux requires writing to some config file (or something like that) and MacOS doesn't actually support custom Uri Schemes, instead Discord has to use a seperate .json file to store this information. For proper cross-platform support, this will need to be accounted for. At the moment it is only using Windows implementation for the sake of simplicity and time constraints I have at the moment.

**Comment by bigworld12** [comment]
i already created a fork with a working .net standard port 
https://github.com/bigworld12/discord-rpc-csharp
the output folders need to be fixed tho since i fucked them up somehow

btw we can target multiple frameworks as i did in the project 
![image](https://user-images.githubusercontent.com/10135395/43459543-1b5389ce-94ce-11e8-81cb-ae2c78d46412.png)

as for the Native pipes and URI scheme implementations we can fix those later, but i think having .net standard as a base library is never a problem

**Comment by GitStonic** [comment]
Any update on this ?

**Comment by Lachee** [comment]
The refactor branch is working towards this with a more universal pipe for Unity3D. There is still some question on support for the register feature and such.

**Comment by Lachee** [comment]
The cross-platform branch supports this now. I just need some testing and bug fixing done for Linux and MacOS as I do not have any machines at my disposal at the moment.

**Comment by Agrair** [comment]
Not sure if this belongs here, but me and a friend are also interested in 64bit support, and 64bit support for mono platforms. When would this become available, if ever?

**Comment by Lachee** [comment]
This has been confirmed to work on MacOS
