### ISSUE TITLE
Buttons on C#

### ISSUE THREAD

**Issue by jurypastes** [Lachee/discord-rpc-csharp#131]
I implemented this:

` DiscordRPC.client.SetPresence(new RichPresence()
                            {
                                
                                Details = "Details",
                                State = $"State",
                                Buttons = new Button()
                                {
                                    Url = "https://google.com",
                                    Label = "Discord Server",
                                },
                                Assets = new Assets()
                                {
                                    LargeImageKey = "imakey",
                                    LargeImageText = "text",
                                    
                                }
                                
                                
                            });`
                            
And im getting this error:
Cannot implicitly convert type 'DiscordRPC.Button' to 'DiscordRPC.Button[]'

**Comment by woke999** [comment]
noob, jk love u

**Comment by Lachee** [comment]
The error perfectly tells you what's wrong.

Buttons is an array, you are trying to assign a single object instead tho

**Comment by jurypastes** [comment]
I don't understand that explanation, i just need a wait to fix it, lol.

**Comment by jurypastes** [comment]
nvm, fixed lol

**Comment by DeathlyBower959** [comment]
how was this fixed? I am having the same problem, and are new to c#

**Comment by AndreZila01** [comment]
I have the same problem, ... NotLikeThis

**Comment by Lachee** [comment]
Buttons are an array.
use an array of buttons. 

If you do not know how arrays work, here is a [BRackeys Tutorial](https://www.youtube.com/watch?v=RQ0JHMGiobo) for C# beginners.

**Comment by AndreZila01** [comment]
@DeathlyBower959 I found one solution...

		DiscordRPC.Button[] btn = new DiscordRPC.Button[1];

		private void Discord(){

			client = new DiscordRpcClient(APPLICATION ID, -1);

			client.Initialize();
			string url = "https://google.com";
			string Botaria = "Botaria";
			btn[0] = JsonConvert.DeserializeObject<DiscordRPC.Button>("{\"Url\":\"" + url + "\", \"Label\":\"" + Botaria + "\"}");
			string temp = "";
			var rp = new RichPresence()
			{
				Details = "",
				State = "",
				Assets = new Assets()
				{
					SmallImageKey = "",
					LargeImageKey = "",
				},
				Buttons = btn,
			};

			rp.Timestamps = new Timestamps(start);
			client.SetPresence(rp);
		}

**Comment by Lachee** [comment]
that is.... one way to do it. 
However a better, cleaner way (that doesn't rely on JSON serialization (seriously dont do that just create the object)) would be the example provided https://github.com/Lachee/discord-rpc-csharp/blob/master/DiscordRPC.Example/Program.cs#L108-L111

```cs
            new RichPresence()
            {
                Details = "A Basic Example",
                State = "In Game",
                Timestamps = Timestamps.FromTimeSpan(10),
                Buttons = new Button[]
                {
                    new Button() { Label = "Fish", Url = "https://lachee.dev/" }
                }
            }
```

**Comment by DeathlyBower959** [comment]
Yeah, I figured that out a while ago, there is no reason to use JSON serialization, there is no point. Lachee's solution is much better, that's what I had originally used, and I'm a little more accustomed to c# now.
