### ISSUE TITLE
[Question] How to do line feed in State (Rich Presence)?

### ISSUE THREAD

**Issue by Ts-Pytham** [Lachee/discord-rpc-csharp#132]
I have a problem, i'm trying to separate 2 texts, the first one with the song name and the second one with the author name but, when i use a line feed between these texts it doesn't seen separated when i check it on Discord but i can see the line feed applied when i put the cursor over the text. Example
![image](https://user-images.githubusercontent.com/43942761/111255893-ef13f680-85e5-11eb-8d5a-f03d4cbb4947.png)

A example on Spotify it seens like this:

![image](https://user-images.githubusercontent.com/43942761/111256059-39957300-85e6-11eb-9a95-e83edfcbdced.png)

**Comment by Lachee** [comment]
if `\n` doesnt work in the text, then discord doesnt support new lines. Unfortunately there is nothing this library can do to resolve that.

**Comment by fenwikk** [comment]
You should put the song name in _Details_ and the artist in _State_. That is the only way you could make a line break in discord rpc

**Comment by OFWModz** [comment]
You need to use Enviroment.NewLine. I know as I use this for my presence and it works.

**Comment by Ts-Pytham** [comment]
> You need to use Enviroment.NewLine. I know as I use this for my presence and it works.

It didn't work, I show you my code:
`discordRP.Details = "Escuchando: ";`
 `discordRP.State = $"{TextBlock_Author_Name.Text}{Environment.NewLine}{Name_Music.Text}";`

Image:

![image](https://user-images.githubusercontent.com/43942761/112017376-8fdd4700-8afb-11eb-8642-c9c454733419.png)

**Comment by Ts-Pytham** [comment]
> You should put the song name in _Details_ and the artist in _State_. That is the only way you could make a line break in discord rpc


For now that is the solution.

**Comment by Kein** [comment]
There is no linebreaks, it just the title of the app is also seems to be changed (so they have title, state and details to use) I dont belive mere mortals can do it, but Spotify is a different talk, guess Discord allow big guy to send title for changes as well.
