### ISSUE TITLE
[BUG] Presence Will Not Set - Very Specific And Complicated Issue

### ISSUE THREAD

**Issue by OFWModz** [Lachee/discord-rpc-csharp#135]
**Describe the bug**
Presence will not set when this is being used in a melonloader mod for a IL2CPP game. Could you add me on discord at Plague#6278 so we can get to the bottom of this, as I feel it is not simple?

**To Reproduce**
Create A MelonLoader Mod For VRChat & Try To Use This Library, It Will Not Work, But Using DllImport On The OG Discord-RPC (C++) Works. - Yes, I embedded your code instead of using a external DLL, which fixes the reference not existing issue.

**Expected behavior**
It working lul

**Desktop (please complete the following information):**
 - OS: Windows 10.
 - Framework: .NET Framework 4.7.2
 - Version: This is irrelevant as it does not change anything here.

**Additional context**
It would be beyond more efficient to find the cause of this on discord than here.

EDIT: Yes, I have made a seperate simple winforms project and tested, my code works fine there and the presence works. It does not when in a MelonLoader mod for VRChat however.

**Comment by OFWModz** [comment]
Here is a test mod for MelonLoader (Latest): 
[discord-rpc-csharp Test Mod.zip](https://github.com/Lachee/discord-rpc-csharp/files/6181215/discord-rpc-csharp.Test.Mod.zip)

**Comment by Lachee** [comment]
If you are using Unity3D, you need to use the Native Named Pipe instead of the default Managed Named Pipe. 
This is a limitation of mono and how it handles pipes (it doesn't, so I wrote my own implementation).


If you want more information from the pipe to see what is causing the issues, I recommend writing a logger to use your `MelonLogger.Msg` and setting it to Verbose (or just using the [Console Logger](https://github.com/Lachee/discord-rpc-csharp/blob/master/DiscordRPC/Logging/ConsoleLogger.cs) )

**Comment by OFWModz** [comment]
I'll look into it and update you if I find anything.

**Comment by OFWModz** [comment]
This is all I got:

INFO: Attempting a new connection
INFO: RPC Connection Started
TRCE: ============================
TRCE: Enqueue Command: DiscordRPC.RPC.Commands.PresenceCommand
TRCE: Assembly:             discord-rpc-csharp Test Mod, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
TRCE: Pipe:                 DiscordRPC.IO.ManagedNamedPipeClient
TRCE: Platform:             Microsoft Windows NT 10.0.18362.0
TRCE: applicationID:        812162424068898836
TRCE: targetPipe:           -1
TRCE: POLL_RATE:            1000
TRCE: _maxRtQueueSize:      512
TRCE: _maxRxQueueSize:      0
TRCE: ============================
TRCE: Connecting to the pipe through the DiscordRPC.IO.ManagedNamedPipeClient
TRCE: ManagedNamedPipeClient.Connection(-1)
TRCE: Connection Attempt 0 ()
INFO: Attempting to connect to discord-ipc-0
TRCE: Waiting for connection...
INFO: Connected to discord-ipc-0
TRCE: Done. Result: False
TRCE: Begining Read of 16384 bytes
TRCE: Connected to the pipe. Attempting to establish handshake...
TRCE: Enqueued Message, but queue size is 0.
TRCE: Attempting to establish a handshake...
TRCE: Sending Handshake...

I'm not sure what is failing here.
For context, this is a MelonLoader mod, VRChat is a Unity3D IL2CPP game, but my assembly is loaded into it.

Any ideas? I really want this working.

**Comment by Lachee** [comment]
> If you are using Unity3D, you need to use the Native Named Pipe instead of the default Managed Named Pipe

probably why it isn't working.

> This is a limitation of mono and how it handles pipes (it doesn't, so I wrote my own implementation).

this is why that wouldn't work.

**Comment by OFWModz** [comment]
Except that native named pipe is not released not made really usable for standalone unity3d injected dlls. I never made VRChat, thus have no editor access. How would I use it in a standalone MelonLoader mod dll?
