### ISSUE TITLE
[BUG] endTimestamp-less elapsed mode payload construction incorrect?

### ISSUE THREAD

**Issue by Kein** [Lachee/discord-rpc-csharp#139]
**Describe the bug**
Specifying only startTimestamp forces RichPresence to have forever bugged 00:00

**To Reproduce**
1. Create basic RichPresence
2. Populate State, Details and StartTimestamp
3. Send
4. Check broken timer in rich presence in the client

**Expected behavior**
According to docs, if endTimestamp is not send, elapsed mode is used, starting from `startTimestamp`

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 1.0.175
 - Discord: Stable 81972 (9bccc1c) Host 1.0.9001

**Comment by Lachee** [comment]
Hello, what are you setting `startTimestamp` too?
Can you please provide a code sample.

**Comment by Kein** [comment]
```cs
presence = new RichPresence();
presence.State = MAINMENU;
presence.Details = string.Empty;
presence.Timestamps = new Timestamps(DateTime.Now, null);
presence.Assets = new DiscordRPC.Assets();
presence.Assets.LargeImageKey = "logo";
client.SetPresence(presence);	
```

I switched back to native lib with basic wrapper around it  - it works as expected, if only start timestamp is sent then it uses "elapsed" mode.

**Comment by Lachee** [comment]
DateTime is UTC. Please use `DateTime.UtcNow`. 

Alternatively, there is a shortcut property:
`Timestamps.Now`
https://github.com/Lachee/discord-rpc-csharp/blob/master/DiscordRPC/RichPresence.cs#L485
