### ISSUE TITLE
Set Presence in VB.NET

### ISSUE THREAD

**Issue by xcfr3sh** [Lachee/discord-rpc-csharp#140]
Hi guys, I have a quick question. How do I set the Rich Presence in VB.NET?

I use the Library for my VB.NET Project and I can setup the Client with the ID and I can Initialize it. But all it sends to Discord Is just the Title of the Application, but how i can set up the Client correctly to send details, assets etc.?

Really appreciate your answers :)

![discord rpc](https://user-images.githubusercontent.com/76883164/115086205-183ce500-9f0c-11eb-8eb3-a28c0799737e.png)

**Comment by Lachee** [comment]
I dont actively support dead languages. However, it is in theory possible to use this library with VB.NET.
Simple send a SetPresence and give it an appropriate RichPresence object as per the example.

Obviously, you will need to convert the C# example into VB.NET, but that shouldn't be too hard.

```cs
	//Set the rich presence
	//Call this as many times as you want and anywhere in your code.
	client.SetPresence(new RichPresence()
	{
		Details = "Example Project",
		State = "csharp example",
		Assets = new Assets()
		{
			LargeImageKey = "image_large",
			LargeImageText = "Lachee's Discord IPC Library",
			SmallImageKey = "image_small"
		}
	});	
```

**Comment by xcfr3sh** [comment]
Thank you very much :)
You helped me out. Here is my code for later readers. ^^ It’s a bit bigger, but it do what it’s supposed to.

```
        'Client
        Dim client As New DiscordRpcClient("YOUR_APPLICATION_ID") 'API KEY
        client.Initialize()

        'Timestamp (Unix Epoch)
        Dim unixtime As ULong = (Date.UtcNow - New DateTime(1970, 1, 1, 0, 0, 0)).TotalSeconds
        Dim rpctimestamps As New Timestamps
        rpctimestamps.StartUnixMilliseconds = unixtime

        'Assets
        Dim rpcassets As New Assets
        rpcassets.LargeImageKey = "large"
        rpcassets.SmallImageKey = "small"
        rpcassets.LargeImageText = "Minecraft Server Tools"
        rpcassets.SmallImageText = "editing..."

        'Final RPC
        Dim rpc As New RichPresence
        rpc.Details = "🟢 Server is Online"
        rpc.State = "Editing the Server"
        rpc.Assets = rpcassets
        rpc.Timestamps = rpctimestamps

        client.SetPresence(rpc)
```

> Final Result:
![discord rpc -2](https://user-images.githubusercontent.com/76883164/115109257-f461b980-9f74-11eb-97f2-e9a1799e313a.png)
