### ISSUE TITLE
Just not working...

### ISSUE THREAD

**Issue by RusJJ** [Lachee/discord-rpc-csharp#144]
C++ Discord RPC works as it should. But this one is NOT.

> private static RichPresence presence = new RichPresence() {
     Details = "In-game researching...",
     State = "Playing"
 };
 client.Initialize(); // Returns true
 client.SetPresence(presence);

That's it.
P.S. OnReady is not called
UPD: OnError too.

**Comment by Lachee** [comment]
Hello there "Just not working" is incredibly vague and unhelpful. I have an issue template for a reason, please follow it.

Feel free to create a new issue with the required information.
