### ISSUE TITLE
[FEATURE REQUEST] Add UpdateButton1 and UpdateButton2

### ISSUE THREAD

**Issue by HAHOOS** [Lachee/discord-rpc-csharp#146]
@Lachee i see you added buttons, but there is no `UpdateButton1` and `UpdateButton2` like:
```csharp
DiscordRpcClient client = new DiscordRpcClient("client-id");
client.UpdateButton1("label", "url");
client.UpdateButton2("label", "url");
```

**Comment by Lachee** [comment]
Because buttons are an array

**Comment by HAHOOS** [comment]
Oh so this will never be added?

**Comment by Lachee** [comment]
Not in the propersition you have presented.
I tend to find it bad form to have Name1, Name2, Name3 etc.

If you had another suggestion on how to implement an update function for buttons, please share :)

**Comment by HAHOOS** [comment]
Ok

**Comment by Founntain** [comment]
> Oh so this will never be added?

Just update them by overriding the array.
If you added them and want to update the first one:

```
var btn1 = new Button();
btn1.Label = "your label";
btn1.Url = "your url";

presence.Buttons[0] = btn1;
```

That's how I do it and it works perfectly fine.

**Comment by HAHOOS** [comment]
**Thanks for help!**
