### ISSUE TITLE
RichPresence from byte[]

### ISSUE THREAD

**Issue by HAHOOS** [Lachee/discord-rpc-csharp#148]
Hey, i got question. How to set RichPresence from byte[]?

**Comment by Lachee** [comment]
There are many different serialization methods available to you. The easiest that comes to mind is to turn it into JSON and they convert that string into a byte array.

**Comment by HAHOOS** [comment]
Thanks @Lachee , but i got question. Do you see my suggestion #147?

**Comment by Lachee** [comment]
yes but i am very busy IRL at the moment. I havn't had a chance to properly review the suggestion and see what would be suitable for the library.

**Comment by HAHOOS** [comment]
Oh ok
