### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Mrgaton** [Lachee/discord-rpc-csharp#152]
**a bug in rpc tryng to change a form label form ready**
![image](https://user-images.githubusercontent.com/68958481/128908593-db2f8e13-7983-4075-ba4b-a5190462ed2b.png)
i have thath code but when i tried to run it i have this error

System.InvalidOperationException: Invalid operation through threads: The control 'BiembenidaLabel' was accessed from a different thread than the one in which it was created.
    in System.Windows.Forms.Control.get_Handle ()
    in System.Windows.Forms.Control.set_WindowText (String value)
    in System.Windows.Forms.Control.set_Text (String value)
    at K1R4FN.K1R4FN. <OnReady> d__34.MoveNext () at C: \ Users \ Mrgato \ source \ repos \ K1R4FN \ K1R4FN \ K1R4FN.cs: line 261

**Comment by Lachee** [comment]
This isn't a bug.

By default, events are emitted on the thread that created them (the IO thread). 
**You cannot update WinForm elements from different threads.**

There are multiple solutions to this problem. A quick google search for the issue would have lead you to [this solution](https://stackoverflow.com/a/661662/5010271). 

The documentation contains further reading about [how events work](https://lachee.github.io/discord-rpc-csharp/docs/articles/getting_started/standard.html#events).
