### ISSUE TITLE
[BUG] Get user Banner

### ISSUE THREAD

**Issue by Mrgaton** [Lachee/discord-rpc-csharp#153]
![image](https://user-images.githubusercontent.com/68958481/129213507-52e32053-86b3-41f3-abc6-5343e5c6e8f9.png)
i cant get user banner via rpc

**Comment by Lachee** [comment]
Correct, banner is not supported by this library.

**Comment by kunseru** [comment]
> Correct, banner is not supported by this library.

is there any way you could add it or

**Comment by Lachee** [comment]
> > Correct, banner is not supported by this library.
> 
> is there any way you could add it or

No, this is a limitation to the Discord API.
![no banner is given in response](https://i.lu.je/2023/devenv_mR4lgg6UjR.png)

If you want this feature you will have to ask Discord Support to give the banner in the user object sent by the RPC.
