### ISSUE TITLE
[FEATURE REQUEST] Current Rich Presence

### ISSUE THREAD

**Issue by julianoBRL** [Lachee/discord-rpc-csharp#157]
I'm opening this because I didn't see it and I didn't find it anywhere, so here goes:

Is there or intends to put some function that takes the Rich Presence of a game different from the application, for example:

there is my application running in the background, so I open GTA for example and my application that is running in the background notices the change that has taken place and executes certain code.

**Comment by Lachee** [comment]
Nope.

This is impossible as Rich Presence is basically set only. The "Current Presence" feature that is implemented in this library simply stores what you have set and when Discord confirms it was set correctly.

If you want this functionality, you will need a bot with privileged intents, sharing a server with the user.
