### ISSUE TITLE
Problem With DiscordRPC Newtonsoft.Json after obfuscate

### ISSUE THREAD

**Issue by fknMega** [Lachee/discord-rpc-csharp#158]
I am using **DiscordRPC**, and I am using **Newtonsoft.Json 13.0.1**

The problem is, after I **obfuscate** my exe, It whows this error: 
![preview](https://cdn.discordapp.com/attachments/840079191071391776/883333008285913128/unknown.png)

**It looks like DiscordRPC really needs the 12.0.0 version of Newtonsoft.Json** , but I have to use 13, 
help?

**Comment by Lachee** [comment]
if you need a specific version of `Newtonsoft.Json`, i recommend building the library yourself. See the [Building Instructions](https://github.com/Lachee/discord-rpc-csharp#building) provided.

TL;DR: Clone the repository and update the nuget package for Newtonsoft.Json, and include that in your project.
