### ISSUE TITLE
Proper external Url support

### ISSUE THREAD

**Issue by Azyyyyyy** [Lachee/discord-rpc-csharp#169]
So discord now allows external url's as the key for assets. While this library itself is working just fine when using external url's, it also starts throwing errors. I'm shortly going to make a PR to sort this issue out but thought it'll be best if I make an issue first :+1:  

As an example here's some response data from discord when using external url's
``Data: {"cmd":"SET_ACTIVITY","data":{"details":"Chilling","assets":{"large_image":"mp:external/Y4Y3FSocOK9fftIsCyFwiM3xDfpQeJXKttMylJJFLJk/https/i.imgur.com/QN5WA4W.png","large_text":"Hmmm coffee"},"name":"the game of life","application_id":"389132961225768961","type":0},"evt":null,"nonce":"1"}``

**Comment by Lachee** [comment]
Resolved in #170
