### ISSUE TITLE
Image asset keys can be way longer than 32

### ISSUE THREAD

**Issue by maximmax42** [Lachee/discord-rpc-csharp#171]
Currently, trying to set a key that's longer than 32 symbols will result in StringOutOfRangeException being thrown, but apparently you can name your assets any name that's up to 999 symbols long. Here's the proof: https://discordapp.com/api/oauth2/applications/896771305108553788/assets.

**Desktop (please complete the following information):**
 - OS: Windows
 - Framework: .NET Framework 4.8
 - Library Version: 1.0.175 (latest on nuget)

**Comment by Lachee** [comment]
Did PR #170 not fix this? Or has the automated builds broken and didnt publish to nuget?

**Comment by maximmax42** [comment]
Latest nuget version is 175 from January 2021.

**Comment by maximmax42** [comment]
Also, #170 only bumps up the max length to 256, which surely will be enough for pretty much everyone, but the true max length seems to be 999.

**Comment by Lachee** [comment]
> Also, #170 only bumps up the max length to 256, which surely will be enough for pretty much everyone, but the true max length seems to be 999.

What discord lets you set via their web api maybe not the same as what they let you set in the RPC API unfortunately . 
I'll check the nuget and builds when i get some time this week. For now if you need a increased 256byte i recommend building yourself using the guide or waiting for the nuget release :)

**Comment by Almighty-Shogun** [comment]
Added to my "Fix list" for PR https://github.com/Lachee/discord-rpc-csharp/issues/176
