### ISSUE TITLE
Is it possible to set an image from http URL ?

### ISSUE THREAD

**Issue by Ombrelin** [Lachee/discord-rpc-csharp#174]
I see in the documentation that you can set an image on the rich presence using a asset id, but is possible to dynamically set an image from its URL ? If yes, how ?

**Comment by Lachee** [comment]
No you cannot, its a limitation on Discords end. You can only upload from the discord developer dashboard and use the id assigned there.

**Comment by Ombrelin** [comment]
Hi, actually it seems that this should be possible :   
[https://www.reddit.com/r/discordapp/comments/rndazc/discord_finally_enabled_the_ability_to_load_rich/](https://www.reddit.com/r/discordapp/comments/rndazc/discord_finally_enabled_the_ability_to_load_rich/)  
Also a few library allow it, like for instance : [https://github.com/EthanC/Perplex](https://github.com/EthanC/Perplex)  
  
However, using DiscordRpcCsharp, I tried to put my http url in the LargeImageKey field and it doesn't work.

**Comment by Lachee** [comment]
This issue is no out of date and since my previous message it has become possible to use image urls. My library has updated its documentation to reflect this fact.

However note that the URL in question must still fit within the 128 byte limitation of the LargeImageKey and must be publically accessible to Discord. If you are trying to use a host like Imgur, you might have some issues.

**Comment by Ombrelin** [comment]
Thanks for the detailed answer !  
I just check the size of my urls (those are PLEX thumbnail urls), and despite them being 202 bytes long, the image is not displayed :thinking: 

![](https://github.com/Lachee/discord-rpc-csharp/assets/47502331/0227ada5-7d26-4100-9032-ef1c5d3ad767)

Would you have any clue of what I am doing wrong ? 

```c#
        return new RichPresence
        {
            Details = $"♫ {session.MediaTitle}",
            State = $"{playerState} {session.MediaGrandParentTitle}",
            Timestamps = new Timestamps
            {
                End = endTimeStamp
            },
            Assets = new Assets()
            {
                LargeImageKey = session.Thumbnail
            }
        };
```
