### ISSUE TITLE
Nuget package is outdated

### ISSUE THREAD

**Issue by Smaltin** [Lachee/discord-rpc-csharp#178]
**Describe the bug**
The nuget package is outdated and is running the January 2021 version of the code

**Expected behavior**
The package should be a more recent version involving the new URL keying for example

**Additional context**
I believe it has to do with the nuget branch on Github being outdated, but I could be wrong.

**Comment by Lachee** [comment]
Yup, this is a known issue. The CI has failed to build and publish the last few nugget packages. 
I am waiting for #117 before I setup the CI and fix the nuget package. 

leaving this issue open as a reminder

**Comment by Almighty-Shogun** [comment]
I can try to fix https://github.com/Lachee/discord-rpc-csharp/issues/117 with my upcoming PR https://github.com/Lachee/discord-rpc-csharp/pull/177 but I can't guarantee anything for 100% sure since I have no acknowledgement and/or idea how unity exactly works

**Comment by sll552** [comment]
Any Progress on this? with the latest nuget package external URLs dont seem to work.

**Comment by Smaltin** [comment]
@sll552 I went ahead and ended up using a local copy which I compiled (since I didn't expect any immediate updates). If you wish to start using the library now, you can use [my compiled copy](https://github.com/jojo2357/Music-Discord-Rich-Presence/raw/master/MDRP/libs/DiscordRPC.dll). 
You can follow progress at https://github.com/Lachee/discord-rpc-csharp/issues/117 (which none has been made any time recently so I suppose that answers your question).
The nuget package is outdated and will remain that way until 117 is resolved
> I am waiting for https://github.com/Lachee/discord-rpc-csharp/issues/117 before I setup the CI and fix the nuget package.

**Comment by Lachee** [comment]
nuget packages are part of gh actions now and wont be out of date anymore
