### ISSUE TITLE
[BUG] Dependabot does not identify this library

### ISSUE THREAD

**Issue by jojo2357** [Lachee/discord-rpc-csharp#179]
Going to [my dependency graph](https://github.com/jojo2357/Music-Discord-Rich-Presence/network/dependencies) shows [this](https://github.com/rachitkataria13/DiscordRichPresence) repository that has no stars, and no releases and no packages. This repo should be referenced instead of that one, and is due to the fact that the Nuget package has a different name than this repository.

see [how this repo shows up in a `.csproj`](https://github.com/jojo2357/Music-Discord-Rich-Presence/blob/master/MDRP/MDRP.csproj#L103-L105) to see how the confusion arises

**Comment by Lachee** [comment]
Well im not really sure how to fix this now. I don't really want to just change the nuget package name because that wouldn't be very friendly to existing projects.

**Comment by jojo2357** [comment]
Would it be possible to make a new package, upload past versions to it and stop updating the current one?

**Comment by Lachee** [comment]
This has been resolved with GitHub remapping it
