### ISSUE TITLE
[Question] Is there any way to set presence priority?

### ISSUE THREAD

**Issue by MistressPlague** [Lachee/discord-rpc-csharp#180]
Say, for example that this is my main displayed presence: 
![Discord_ikMn5xG722](https://user-images.githubusercontent.com/36628963/156543060-9435c40a-e120-4b72-9bda-d9cb3d38bce4.png)
that is overriding the one I want to be main.

Is there any way to make my presence I create take priority and display on user popout instead of what is above?

I also noticed SteamId isn't implemented, why is this? It's use extends to above as it can replace said game presence.

**Comment by MistressPlague** [comment]
I also noticed SteamId isn't implemented, why is this? It's use extends to above as it can replace said game presence.

**Comment by Lachee** [comment]
no. First Open, First Displayed.
This is a limitation with Discord

**Comment by MistressPlague** [comment]
And what about the SteamId implementation? That question wasn't answered properly. There's a property, but it leads to nothing and is used nowhere?

**Comment by Lachee** [comment]
question was answered: no you cannot set priority presence. First in, first display. Limitation on the official Discord Client, not this library.

Steam ID is used for registration of URI schemes for the "Join" and "Spectate" feature.

**Comment by MistressPlague** [comment]
I am referring to [This](https://github.com/Lachee/discord-rpc-csharp/blob/master/DiscordRPC/DiscordRpcClient.cs#L36)

**Comment by Lachee** [comment]
> I am referring to [This](https://github.com/Lachee/discord-rpc-csharp/blob/master/DiscordRPC/DiscordRpcClient.cs#L36)

Refer to [the documentation](https://lachee.github.io/discord-rpc-csharp/docs/api/DiscordRPC.DiscordRpcClient.html#DiscordRPC_DiscordRpcClient_RegisterUriScheme_System_String_System_String_). That is set via RegisterUriScheme (hence why it's private set)
