### ISSUE TITLE
Buttons that open a URL not working. Removed feature ?

### ISSUE THREAD

**Issue by RaymondTH** [Lachee/discord-rpc-csharp#181]
When using the basic example

  // == Set the presence
            client.SetPresence(new RichPresence()
            {
                Details = "A Basic Example",
                State = "In Game",
                Timestamps = Timestamps.FromTimeSpan(10),
                Buttons = new Button[]
                {
                    new Button() { Label = "Fish", Url = "https://lachee.dev/" }
                }
            });

The presence shows but the button does not work in the latest discord canary client.

Is this happening to anyone else ? Any workarounds ?

**Comment by maximmax42** [comment]
Buttons will not work in your own presence, but will for others. It's a discord's bug/feature.
