### ISSUE TITLE
[Feature] add EndTimestamp

### ISSUE THREAD

**Issue by J0nathan550** [Lachee/discord-rpc-csharp#198]
Original Discord SDK had 'EndTimestamp' could be useful to create "music" applications. Or some games that require EndTimestamp.

**Comment by Lachee** [comment]
End Timestamp is implemented and displays time remaining as per the RPC spec. 

If you want the progress bar as seen in some music applications, you need to be called Spotify and have a specific edge case programmed into the discord client for your company and program.

If this is no longer the case, feel free to comment with the relevant RPC documentation and I will reopen this as a feature request 👍 

If you cannot figure out how to use the remaining time, check the example here:
https://github.com/Lachee/discord-rpc-csharp/blob/master/DiscordRPC.Example/Program.cs#L107
or here:
https://github.com/Lachee/discord-rpc-csharp/blob/master/DiscordRPC.Example/Program.cs#L182-L186
or check the documentation here:
https://lachee.github.io/discord-rpc-csharp/docs/api/DiscordRPC.Timestamps.html#DiscordRPC_Timestamps_End
