### ISSUE TITLE
[BUG] Cannot install Discord RPC package for unity.

### ISSUE THREAD

**Issue by J0nathan550** [Lachee/discord-rpc-csharp#199]
I tried to install Discord RPC nuget package for Unity. but have an issue where Unity says that I don't Discord RPC namespace. When I installed Discord RPC package. What to do in this case? Also tried to install localy but still I had no luck on installing this library.

**Comment by Lachee** [comment]
dont use the nuget package for unity, use the unitypackage.
Since this project needs an update in its build pipeline, you will have to build the package manually for now:
https://github.com/Lachee/discord-rpc-csharp#building
