### ISSUE TITLE
[BUG] Updating details not working

### ISSUE THREAD

**Issue by Kyro999** [Lachee/discord-rpc-csharp#205]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Desktop (please complete the following information):**
 - Framework: [e.g. dotnet core 3 / .net fx 4.5 / Unity 5 .NET 2.0 Subset / Unity 2020 .NET Standard / Monogame ]
 - Library Version: [ e.g. 0.202 ]
 
**Additional context**

**Logs**
```
Provide your logs or a link to the logs here. Make sure you have at least LogLevel.Info enabled.
```
![Capture](https://user-images.githubusercontent.com/81608042/188484591-80e416f2-9f99-4c8c-b51b-f54f70944085.PNG)
![Capture](https://user-images.githubusercontent.com/81608042/188484638-1c449e3b-87fb-444a-80e1-e35d8b0c0ceb.PNG)

**Comment by Kyro999** [comment]
bruh wtf it deleted everytying i just wrote

**Comment by Kyro999** [comment]
for fuck sakes man.

the rpc just doesnt update when you try updating it using a string (field) from another class

**Comment by Kyro999** [comment]
it doesn't work updating it in general

**Comment by Lachee** [comment]
no need for that language lol.
Please provide logs from the RPC.

> the rpc just doesnt update when you try updating it using a string (field) from another class
It doesn't matter if it comes from a field, property, or method from another class. C# copies the string regardless to UpdateDetails

**Comment by Kyro999** [comment]
where is the logs located

**Comment by Lachee** [comment]
You will need to add the FileLogger to your constructor. You should be able to see an example in either the ReadMe or suplimentry example project (sorry docfx is broken atm)

**Comment by Kyro999** [comment]
na i fixed it, i was creating a new instance of the form instead of getting the one i alr had
