### ISSUE TITLE
[HELP] RPC Not showing up in discord

### ISSUE THREAD

**Issue by EnumInt** [Lachee/discord-rpc-csharp#211]
I am following the usage guide and successfully running code, however my custom discord rpc is not showing up, I am making a mod for a c# framework called "melonloader", it runs on top of a unity game. 

[discordlog.txt](https://github.com/Lachee/discord-rpc-csharp/files/9742227/discordlog.txt)
[codesnip.txt](https://github.com/Lachee/discord-rpc-csharp/files/9742230/codesnip.txt)

Also, LoadRPC is being called from a function that runs when the mod is loaded, Im getting stuff from the log about discord, but nothing showing up, maybe I did not setup the pipe properly? I also have game activity enabled, im sorry if this is a stupid question, im trying my best here. thanks :)

**Comment by EnumInt** [comment]
used offical discord sdk, fixed it.

**Comment by Lachee** [comment]
Using another library is not considered a fix for this one as a fyi

**Comment by EnumInt** [comment]
True, i’ll keep that in mind. Sorry about that!
