### ISSUE TITLE
[FEATURE REQUEST] Adding back .Net Framework 3.5 and maybe .Net 6

### ISSUE THREAD

**Issue by DavidCarbon** [Lachee/discord-rpc-csharp#215]
**Describe the feature request**
- Adding .Net Framework 3.5 and/or .Net 6 support

**Reason**
When compiling for .Net Framework Legacy applications, the library now includes additional support files in-order to have it run. Previously it was only one file that was needed to be included when compiling, but now increases the file size of the application.
I noticed in commit https://github.com/Lachee/discord-rpc-csharp/commit/7979aa76a8a77b753aadf4cef340c79f997c0f5c you had updated your scripts and along with it removed .Net Framework 3.5

**Question**
Do you have plans to add .Net Framework 3.5 and/or .Net 6 when compiling the library before pushing to NuGet?

Thanks

**Comment by Lachee** [comment]
.NET 3.5 is pretty dang old now. I am willing to go down to .NET 4.5 again if you want FX.

As for .NET 6 support, i am not well versed enough to comment on that; I will wait for it to be more widespread before attempting to add support (.NET Standard 2.0 hasnt even been fully converted and it is now deprecated by MS).

Leaving this note here for anyone wanting a good first issue:
Help is very much appreciated to add support for these frameworks.

**Comment by Lachee** [comment]
@DavidCarbon could you try this commit? 
https://github.com/Lachee/discord-rpc-csharp/commit/177f62ef789ed4afeaea9708a871f018620835e9

I am unable to get .NET FX running correctly on my machine at this time to verify it is fixed.

**Comment by DavidCarbon** [comment]
Sure, let me try to compile the library on my end and report back my findings

**Comment by DavidCarbon** [comment]
Compiled the library and was able to confirm that .NET FX projects does not lead to additional (support) files.

**Comment by Lachee** [comment]
so... this is a good fix for your needs? if so then I will push this to main branch :)

**Comment by DavidCarbon** [comment]
Yes, the fix is a good candidate to be pushed in the master branch since it is able to maintain support for users that still target .NET FX. Thanks :D

**Comment by pizzaboxer** [comment]
Trying to develop a .NET 6 application, and targeting packs for .NET Framework 4.5 don't actually exist for download. Wouldn't targeting 4.5.2 instead be better?

**Comment by Lachee** [comment]
Just updated the nuget package.


> Trying to develop a .NET 6 application, and targeting packs for .NET Framework 4.5 don't actually exist for download. Wouldn't targeting 4.5.2 instead be better?

Im not sure i follow, the FX 4.5 package should work for your FX 4.5.2 install

**Comment by pizzaboxer** [comment]
Nope, installing the 4.5.2 SDK just didn't work for some reason -- had to follow [this](https://stackoverflow.com/a/70109092) instead.
