### ISSUE TITLE
System.NullReferenceException - _stream was null

### ISSUE THREAD

**Issue by MorGuux** [Lachee/discord-rpc-csharp#22]
Hi, i've recently been looking at some libraries to add Discord Rich Presence support for C#, and I came across your library as the most complete one. I've downloaded your master branch and built the .dll, copied into the program of choice (I'm trying to make a plugin for a sim racing program called SimHub), referenced in VS. 

I've looked at the DiscordRPC.Example code and copied what's relevant into my .CS file. Now when I run the code, it opens up the program, then shortly after, breaks with an unhandled exception 

`System.NullReferenceException: 'Object reference not set to an instance of an object.'`

`_stream was null.`

I have re-written everything a few times, but this error is one I cannot get past.

System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Discord RPC
  StackTrace:
   at DiscordRPC.IO.ManagedNamedPipeClient.Close() in C:\Users\morga\Downloads\discord-rpc-csharp-master\Discord RPC\IO\ManagedNamedPipeClient.cs:line 218
   at DiscordRPC.IO.ManagedNamedPipeClient.Dispose() in C:\Users\morga\Downloads\discord-rpc-csharp-master\Discord RPC\IO\ManagedNamedPipeClient.cs:line 233
   at DiscordRPC.RPC.RpcConnection.MainLoop() in C:\Users\morga\Downloads\discord-rpc-csharp-master\Discord RPC\RPC\RpcConnection.cs:line 369
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

Any help would be greatly appreciated.

Cheers,
Morgan

**Comment by Lachee** [comment]
Hello, I have pushed a commit that will prevent it from crashing. More information leading up to the crash would be appreciated too to help avoid it in the future. Did you close the stream yourself? Requesting for DiscordRPC to close? Or was this a unrequested shutdown, in which case what was the message logged before the crash? Make sure you include the logger to be Logging.LogLevel.Info for the most information possible from the stream.

**Comment by MorGuux** [comment]
No, I uncommented the client.Dispose() command just to make sure it wasn't being run, it was just when the code was run to initialize and set the presence.

**Comment by MorGuux** [comment]
I'm not using a console program but a GUI, so should I change new ConsoleLogger() to something else, so I can see messages in the VS Output?

**Comment by MorGuux** [comment]
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Discord RPC
  StackTrace:
   at DiscordRPC.IO.ManagedNamedPipeClient.EndRead(IAsyncResult callback) in C:\Users\morga\Downloads\discord-rpc-csharp-master (3)\Discord RPC\IO\ManagedNamedPipeClient.cs:line 115
   at System.IO.Pipes.PipeStream.AsyncPSCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)

New error :D

**Comment by Lachee** [comment]
Alright, fixed that weird error too. It seems like your pipe is disposing of itself early. I have also created a FileLogger for you to try too. This is a very inefficient logger, but it will be helpful for debugging. You can find its usage in the example project commented out about the normal ConsoleLogger.

**Comment by MorGuux** [comment]
Just reinstalled everything and basically started from scratch, just to be sure. With the Logging.FileLogger, I have to change it to DiscordRPC.Logging.FileLogger, in order for it to find it. Ran the program and nothing happens. Looked in the newly created log file and this is what it says.


INFO: Attempting a new coonnection

INFO: Initiated shutdown procedure

INFO: Initializing Thread. Creating pipe object.

INFO: Left Main Loop

WARN: Stream was closed, but no stream was available to begin with!

INFO: Thread Terminated

**Comment by MorGuux** [comment]
`using GameReaderCommon;
using SimHub.Plugins;
using System;
using System.Windows.Forms;
using System.Windows.Controls;
using DiscordRPC;
using DiscordRPC.Converters;
using DiscordRPC.Events;
using DiscordRPC.Helper;
using DiscordRPC.IO;
using DiscordRPC.Logging;
using DiscordRPC.Message;
using DiscordRPC.RPC;
using DiscordRPC.Web;

namespace User.PluginSdkDemo
{
    
    [PluginName("Demo plugin")]
    public class DataPluginDemo : IPlugin, IDataPlugin, IWPFSettings
    {
        private int SpeedWarningLevel = 100;
		private static int DiscordPipe = -1;
		private static string ClientID = "424087019149328395";
		private static DiscordRPC.Logging.LogLevel DiscordLogLevel = DiscordRPC.Logging.LogLevel.Info;
		private static RichPresence presence = new RichPresence()
		{
			Details = "Example Project",
			State = "csharp example",
			Assets = new Assets()
			{
				LargeImageKey = "image_large",
				LargeImageText = "Lachee's Discord IPC Library",
				SmallImageKey = "image_small"
			}
		};

		private static DiscordRpcClient client;

		/// <summary>
		/// Instance of the current plugin manager
		/// </summary>
		public PluginManager PluginManager { get; set; }

        /// <summary>
        /// called one time per game data update
        /// </summary>
        /// <param name="pluginManager"></param>
        /// <param name="data"></param>
        public void DataUpdate(PluginManager pluginManager, ref GameData data)
        {
			if (client != null)
				client.Invoke();

			pluginManager.SetPropertyValue("CurrentDateTime", this.GetType(), DateTime.Now);

            if (data.GameRunning)
            {
                if (data.OldData != null && data.NewData != null)
                {
                    if (data.OldData.SpeedKmh < SpeedWarningLevel && data.OldData.SpeedKmh >= SpeedWarningLevel)
                    {
                        pluginManager.TriggerEvent("SpeedWarning", this.GetType());
                    }
                }
            }
        }

        /// <summary>
        /// Called at plugin manager stop, close/displose anything needed here !
        /// </summary>
        /// <param name="pluginManager"></param>
        public void End(PluginManager pluginManager)
        {
			//client.Dispose();
		}

        /// <summary>
        /// Return you winform settings control here, return null if no settings control
        /// 
        /// </summary>
        /// <param name="pluginManager"></param>
        /// <returns></returns>
        public System.Windows.Forms.Control GetSettingsControl(PluginManager pluginManager)
        {
            return null;
        }

        public System.Windows.Controls.Control GetWPFSettingsControl(PluginManager pluginManager)
        {
            return new SettingsControlDemo();
        }

        /// <summary>
        /// Called after plugins startup
        /// </summary>
        /// <param name="pluginManager"></param>
        public void Init(PluginManager pluginManager)
        {
			using (client = new DiscordRpcClient(ClientID, false, DiscordPipe))
			{
				System.IO.File.WriteAllBytes("discord-rpc.log", new byte[0]);
				client.Logger = new DiscordRPC.Logging.FileLogger("discord-rpc.log") { Level = DiscordLogLevel };

				client.SetPresence(presence);
				client.Initialize();
			}

			pluginManager.AddProperty("CurrentDateTime", this.GetType(), DateTime.Now);

            pluginManager.AddEvent("SpeedWarning", this.GetType());

            pluginManager.AddAction("IncrementSpeedWarning", this.GetType(), (a, b) =>
            {
                this.SpeedWarningLevel++;
            });

            pluginManager.AddAction("DecrementSpeedWarning", this.GetType(), (a, b) =>
            {
                this.SpeedWarningLevel--;
            });
        }
    }
}`

This is the code that i'm using in it's entirety. The Init method I have been assured (by simhub developer) only runs once on startup. I have commented out the client.Dispose() in the End() void just to make sure it wasn't being triggered. All I have done prior to this was build the DiscordRPC.dll file, copy the .dll, .pcb and .xml to the simhub directory, and reference it in the VS solution.

**Comment by Lachee** [comment]
```
using (client = new DiscordRpcClient(ClientID, false, DiscordPipe))
			{
				System.IO.File.WriteAllBytes("discord-rpc.log", new byte[0]);
				client.Logger = new DiscordRPC.Logging.FileLogger("discord-rpc.log") { Level = DiscordLogLevel };

				client.SetPresence(presence);
				client.Initialize();
			}

```
You are using a `using` statement. This structure will dispose of the obejct within the using() when the block ends. So what you want to do is add back the End and remove the using so it is like this:
```
client = new DiscordRpcClient(ClientID, false, DiscordPipe);
			
				System.IO.File.WriteAllBytes("discord-rpc.log", new byte[0]);
				client.Logger = new DiscordRPC.Logging.FileLogger("discord-rpc.log") { Level = DiscordLogLevel };

				client.SetPresence(presence);
				client.Initialize();
			

```

**Comment by MorGuux** [comment]
Thank you very much Lachee, after I sorted out a quick issue with NewtonSoft.JSON.dll version mismatch, it works fine.

Cheers for the patience and co-operation. I have developed a program myself and I know what it can be like helping users out. I appreciate your support.

Cheers,
Morgan
