### ISSUE TITLE
[BUG] DiscordRPC.xml not found

### ISSUE THREAD

**Issue by asradesigning** [Lachee/discord-rpc-csharp#225]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Desktop (please complete the following information):**
 - Framework: [e.g. dotnet core 3 / .net fx 4.5 / Unity 5 .NET 2.0 Subset / Unity 2020 .NET Standard / Monogame ]
 - Library Version: [ e.g. 0.202 ]
 
**Additional context**

**Logs**
```
Provide your logs or a link to the logs here. Make sure you have at least LogLevel.Info enabled.
```

**Comment by Lachee** [comment]
Issue has not been filled out correctly and the DiscordRPC.xml is generated on build and is additionally provided in the releases such as https://github.com/Lachee/discord-rpc-csharp/releases/tag/v1.1.3
