### ISSUE TITLE
Need help i cant figure out the assets

### ISSUE THREAD

**Issue by FearlessNite345** [Lachee/discord-rpc-csharp#226]
so i have a WPF app and i dont know what i type in for the image assets for the RPC and i am confused cause if its a image having a image less than 256 bytes is like very very small if someone could please help me that would be great

**Comment by Lachee** [comment]
You upload assets to your application on the discord [developer portal](https://discord.com/developers/applications)

What you put into the field is the `key` of the image. So for example, if i wanted the Red C# icon i would put `image_large_3`

![image](https://i.lu.je/2023/firefox_GFG6d4tCsS.png)
