### ISSUE TITLE
[Feature Request] Add other statuses

### ISSUE THREAD

**Issue by galaxine-senpai** [Lachee/discord-rpc-csharp#231]
Hello there, I saw that you only support one status whereas the discord doc's list multiple statuses (Idle, DnD, Watching, Listening, Etc.) I feel like this wouldn't be hard to implement and would greatly improve usability within your code.

I came across this issue while looking at another GitHub repo which used your library.

**Comment by Lachee** [comment]
https://github.com/Lachee/discord-rpc-csharp/issues/209
https://github.com/Lachee/discord-rpc-csharp/issues/195
https://github.com/Lachee/discord-rpc-csharp/issues/98

Not possible with Rich Presence. It can only have Playing.
