### ISSUE TITLE
New Discord nicknames system

### ISSUE THREAD

**Issue by Vincentsgm** [Lachee/discord-rpc-csharp#234]
Hello, it appears that since the Discord update that removes discriminators from usernames, the RPC client never gets ready.
The event `DiscordRpcClient.OnConnectionFailed` is raised.

**Comment by Lachee** [comment]
It _should_ work without specific changes (i've tested it myself).

It is on my todo to implement the display names, however i am waiting for discord to respond as the RPC does not get this information.
