### ISSUE TITLE
change to system.text.json instead of newsoft json

### ISSUE THREAD

**Issue by Mrgaton** [Lachee/discord-rpc-csharp#238]

**Comment by Lachee** [comment]
No.

You given no reason, no benefits, and no thought of compatibility with Unity3D. If you wish to suggest a fundamental change, please provide more information on why it needs to be done.

If you wish to use another JSON library, feel free to fork and make a build for your use case. I already recommend this when people need specific versions of Newtonsoft.Json than the one provided on NuGet :)
