### ISSUE TITLE
Unable to load file or composition Discord RPC

### ISSUE THREAD

**Issue by Hampusm** [Lachee/discord-rpc-csharp#24]
Unmanaged exception: System.IO.FileNotFoundException: Unable to load file or composition Discord RPC, Version = 1.0.0.0, Culture = neutral, PublicKeyToken = null, or one of its dependencies. The file can not be found.
    at DiscordRPCTest.Program.Main (String [] args)

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using DiscordRPC;

namespace DiscordRPCTest
{
    class Program
    {
        public static DiscordRpcClient client;

        static void Main(string[] args)
        {
            client = new DiscordRpcClient("458202823641792512", true, 1);

            //Subscribe to events
            client.OnPresenceUpdate += (sender, e) =>
            {
                Console.WriteLine("Received Update! {0}", e.Presence);
            };

            //Connect to the RPC
            client.Initialize();

            //Set the rich presence
            client.SetPresence(new RichPresence()
            {
                Details = "CrunchyHub",
                State = "csharp example",
                Assets = new Assets()
                {
                    LargeImageKey = "image_large",
                    LargeImageText = "Lachee's Discord IPC Library",
                    SmallImageKey = "image_small"
                }
            });
            Console.ReadLine();
        }
    }
}
```

**Comment by Hampusm** [comment]
@Lachee Thank you for answering! I am installing
Newtonsoft.Json now. I have a question. What is the DiscordPipe? I just put a random number there (1).

**Comment by Hampusm** [comment]
Update: I installed Newtonsoft but still get a error

Unmanaged exception: System.IO.FileNotFoundException: Unable to load file or composition Discord RPC, Version = 1.0.0.0, Culture = neutral, PublicKeyToken = null, or one of its dependencies. The file can not be found. at DiscordRPCTest.Program.Main (String [] args)

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using DiscordRPC;
using Newtonsoft;

namespace DiscordRPCTest
{
    class Program
    {
        public static DiscordRpcClient client;

        static void Main(string[] args)
        {
            client = new DiscordRpcClient("458202823641792512", true, 1);

            //Subscribe to events
            client.OnPresenceUpdate += (sender, e) =>
            {
                Console.WriteLine("Received Update! {0}", e.Presence);
            };

            //Connect to the RPC
            client.Initialize();

            //Set the rich presence
            client.SetPresence(new RichPresence()
            {
                Details = "CrunchyHub",
                State = "csharp example",
                Assets = new Assets()
                {
                    LargeImageKey = "image_large",
                    LargeImageText = "Lachee's Discord IPC Library",
                    SmallImageKey = "image_small"
                }
            });
            Console.ReadLine();
        }
    }
}
```

**Comment by Lachee** [comment]
Discord Pipe is the pipe number that discord is currently hosted on. It can be 0 to 9. Setting it to -1 will let the library to automatically scan for discord through those pipes.

What version of .NET are you working with? Are you using .NET Standard or a older version?

**Comment by Lachee** [comment]
I think I found the solution hopefully. So in Visual Studio when you add the assembly, you need to make the library "Copy to Local". It should look similar to the following image:
![Visual Studio Project View](https://s.lu.je/Evecord_-_Microsoft_Visual_Studio_2018-06-18_22.11.33.png)

**Comment by Hampusm** [comment]
.Net Framework 4.6.1 and yes, i have copy local enabled but it still doesn't work

**Comment by Hampusm** [comment]
And i dont have it as a assembly i have it as a reference. It's a console application

**Comment by Hampusm** [comment]
Made a github repo https://github.com/Hampusm/DiscordRPC-Csharp-test

**Comment by Hampusm** [comment]
@Lachee

**Comment by Lachee** [comment]
@Hampusm found the problem. Your filename is `DiscordRPC.dll`, however when you build the library it outputs `Discord RPC.dll` and .NET expects the space in the filename.

I have just made made a commit which changes the assembly name from `Discord RPC.dll` to `DiscordRPC.dll`, so I recommend you rebuild the library and replace our previous .dll with the new one.

**Comment by Hampusm** [comment]
Just to let you know. Dont close the issue yet i dont know it it works yet. i am cloning rn

**Comment by Lachee** [comment]
Just updated my comment to be a bit clearer about the issue.

**Comment by Hampusm** [comment]
Got it to work now! Thank you @Lachee for the help!

**Comment by Hampusm** [comment]
Never mind it doesnt work. No error or anything discord just doesnt say anything
![dontwork](https://user-images.githubusercontent.com/25064782/41548767-247d204e-7324-11e8-8d56-a154a1777dc7.png)

**Comment by Hampusm** [comment]
https://github.com/Hampusm/DiscordRPC-Csharp-test

**Comment by Hampusm** [comment]
@Lachee

**Comment by Hampusm** [comment]
Nvm it works
