### ISSUE TITLE
Adding support for custom activity type

### ISSUE THREAD

**Issue by PixelHir** [Lachee/discord-rpc-csharp#251]
Discord Rich Presence [now supports](https://x.com/advaithj1/status/1816655583107510517?s=46) activities other than just „Playing”. Support for those could be potentially implemented into this library as well?
https://github.com/discordjs/RPC/pull/149

**Comment by Lachee** [comment]
Yup i will be adding this over the weekend. Advaith pinged me to be aware.

**Comment by Hazzz895** [comment]
> Yup i will be adding this over the weekend. Advaith pinged me to be aware.

when
