### ISSUE TITLE
Timestamps adds 4 hours?

### ISSUE THREAD

**Issue by Codingale** [Lachee/discord-rpc-csharp#26]
using the code
```
Timestamps = new Timestamps()
{
        Start = DateTime.Now,
        End = null
}
```

produces results like:
![Image showing 4 hours](https://i.imgur.com/c0uuLJN.png)

It's adding on an extra four hours to this? Is this a timezone issue or something? Do I need to do

`DateTime.Now.AddHours` to compensate on every client or something? Just started using RPC, so I might be missing something.

**Comment by Hampusm** [comment]
Why did you add `End = null`?
And the DateTime should be UtcNow.

**Here's the [example](https://github.com/Lachee/discord-rpc-csharp/blob/master/DiscordRPC.Example/Program.cs):**
```
presence.Timestamps = new Timestamps()
				{
					Start = DateTime.UtcNow
				};
```

**Comment by Lachee** [comment]
Times are Discord based (so UTC+0 timezone), using `DateTime.Now` will use the users current time and not UTC, so there will be the timezone offset to all the timings. As @Hampusm suggested, it is better to use `DateTime.UtcNow` as that already accounts for the timezone offset.

Also adding null to end is optional. You can do it if you wish for clarity, but it is not necessary, as behind the scenes it defaults to null anyways :)

**Comment by Codingale** [comment]
Oh the `End = null` was left over when I was testing to see if it changed or crashed as I thought maybe it would break or something. Just messing around with it to see what all would happen and just forgot to  erase it :P


Thanks, didn't know about `DateTime.UtcNow`
