### ISSUE TITLE
Only need to check for HasRegisteredUriScheme if Join/JoinRequest or Spectate are requested - type can be None which causes this to raise an exception by mistake

### ISSUE THREAD

**Issue by Tenebrous** [Lachee/discord-rpc-csharp#27]
https://github.com/Lachee/discord-rpc-csharp/blob/f99844cf5ffdb001709acf6d5ee0c7c41d193ad7/Discord%20RPC/DiscordRpcClient.cs#L536

**Comment by Lachee** [comment]
After reviewing the logic and the purpose of the function, I have added a `EventType.None` check to ignore trying to subscribe (and avoiding the URI Scheme check) when there is no differences between subscribe and its stored type.

**Comment by Tenebrous** [comment]
Perfect :)
