### ISSUE TITLE
 TypeLoadException

### ISSUE THREAD

**Issue by Trigger-edge** [Lachee/discord-rpc-csharp#30]
Hello I have this error when I press play button: 

(I put DiscordRPC.dll on Assets/Plugins/ and DiscordRPC.Native.dll on ProjectFolder/ with Unity 5.6.6f2)

TypeLoadException: Could not load type 'DiscordRPC.RPC.Payload.EventPayload' from assembly 'DiscordRPC, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
System.Reflection.MonoMethodInfo.GetMethodInfo (IntPtr handle) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:59)
System.Reflection.MonoMethodInfo.GetAttributes (IntPtr handle) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:75)
System.Reflection.MonoMethod.get_Attributes () (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:245)
System.Reflection.MethodBase.get_IsSpecialName () (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:184)
UnityEditor.Build.BuildPipelineInterfaces.InitializeBuildCallbacks (Boolean findBuildProcessors, Boolean findSceneProcessors) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildPipelineInterfaces.cs:150)

**Comment by Hampusm** [comment]
Do you have Newtonsoft Json?

**Comment by Hampusm** [comment]
And could you also post the code or a link to the code?

**Comment by Trigger-edge** [comment]
Sorry that´s was my bad, I solve by replacing my old json library version by the one provided in your project.
