### ISSUE TITLE
DllNotFoundException

### ISSUE THREAD

**Issue by Trigger-edge** [Lachee/discord-rpc-csharp#31]
Using Unity 5.6.6f2 (32-bits), I manually copied DiscordRPC.Native.dll in my project root folder:

Log1: <IPC> Unhandled Exception: System.DllNotFoundException
UnityEngine.Debug:LogError(Object)
UnityLogger:Error(String, Object[]) (at Assets/Scripts/Discord/Control/UnityLogger.cs:28)
DiscordRPC.RPC.RpcConnection:MainLoop()

Log2: <IPC> DiscordRPC.Native.dll
UnityEngine.Debug:LogError(Object)
UnityLogger:Error(String, Object[]) (at Assets/Scripts/Discord/Control/UnityLogger.cs:28)
DiscordRPC.RPC.RpcConnection:MainLoop()

**Comment by Hampusm** [comment]
You know. It's easier to help you with a little more than just a error code

**Comment by Lachee** [comment]
Sorry, the readme might be a little out date and I havn't run it in Unity 5 in ages. Try copying the dll to the plugins folder instead, under `assets/plugins/`. You may need to further seperate them into x86 and x86_64 folders
