### ISSUE TITLE
Updating presence 

### ISSUE THREAD

**Issue by Joe112Carlos** [Lachee/discord-rpc-csharp#35]
Hello, 
`client.invoke()` invokes 
`client.OnPresenceUpdate()` but i dont know how i update the actual presence, it says Received update DiscordRpc.Richpresence but it does not actually update and i dont know how to do it.

**Comment by Lachee** [comment]
```csharp
	//Set the rich presence
	client.SetPresence(new RichPresence()
	{
		Details = "Example Project",
		State = "csharp example",
		Assets = new Assets()
		{
			LargeImageKey = "image_large",
			LargeImageText = "Lachee's Discord IPC Library",
			SmallImageKey = "image_small"
		}
	});	
```

**Comment by Joe112Carlos** [comment]
`client.OnPresenceUpdate += (sender, e) =>
            {
                Console.WriteLine("Received Update {0}", e.Presence);
                client.SetPresence(new DiscordRPC.RichPresence()
                {
                    Details = "details",
                    State = "state",
                    Assets = new DiscordRPC.Assets()
                    {
                        LargeImageKey = "sourcecodediscord",
                        LargeImageText = largetext,
                        SmallImageKey = "sourcecodediscord"
                    }

                });` gets called on button click `private void button3_Click_2(object sender, EventArgs e)
        {
            client.Invoke();
            
        }` largetext is getting defined by a textbox, thats why i want to update on button press so i can change the Text for the largeimage, so i pasted `client.SetPresence(new DiscordRPC.RichPresence()
                {
                    Details = "details",
                    State = "state",
                    Assets = new DiscordRPC.Assets()
                    {
                        LargeImageKey = "sourcecodediscord",
                        LargeImageText = largetext,
                        SmallImageKey = "sourcecodediscord"
                    }

                });` under `client.OnPresenceUpdate += (sender, e) =>`

**Comment by Joe112Carlos** [comment]
so should i just set the new presence directly on the button click? and why would i need client.invoke() if i do paste the set presence part directly on the button.Also, will it overwrite the old rpc?

**Comment by Joe112Carlos** [comment]
Alright thanks!:)
