### ISSUE TITLE
I Can't update. help me plz

### ISSUE THREAD

**Issue by cimpdev** [Lachee/discord-rpc-csharp#37]
`        private void button1_Click(object sender, EventArgs e)
        {
            client = new DiscordRpcClient(ClientID, true, DiscordPipe);

            client.OnPresenceUpdate += (sender2, e2) =>
            {
                richTextBox1.Text += e2.Presence;
            };

            if (button1.Text == "Connect")
            {
                presence.Details = textBox1.Text;

                presence.Timestamps = new Timestamps()
                {
                    Start = DateTime.UtcNow
                };

                presence.Party = new Party()
                {
                    ID = Secrets.CreateFriendlySecret(new Random()),
                    Size = 1,
                    Max = 4
                };

                client.SetPresence(presence);

                client.Initialize();

                Properties.Settings.Default.Details = textBox1.Text;
                Properties.Settings.Default.Stats = textBox2.Text;
                Properties.Settings.Default.LImageText = textBox5.Text;
                Properties.Settings.Default.SImageText = textBox6.Text;

                Properties.Settings.Default.LImageKey = comboBox1.SelectedIndex;
                Properties.Settings.Default.SImageKey = comboBox2.SelectedIndex;
                Properties.Settings.Default.Save();

                button1.Text = "Update";
            }
            else
            {
                presence.Details =  textBox1.Text;

                client.SetPresence(presence);
            }
        }`

**Comment by Lachee** [comment]
Havent responded in 2 weeks and I believe this is the issue he was facing. Closed.
