### ISSUE TITLE
Program.cs

### ISSUE THREAD

**Issue by DopeDealers** [Lachee/discord-rpc-csharp#39]
error 
`DiscordRPC.dll'. Cannot find or open the PDB file.`

i have the pdb file within the output folder

this is my program.cs file

`class Program
    {
        public static DiscordRpcClient client;

        static void Main(string[] args)
        {
            client = new DiscordRpcClient("id", true, 1);

            //Subscribe to events
            client.OnPresenceUpdate += (sender, e) =>
            {
                Console.WriteLine("Received Update! {0}", e.Presence);
            };

            //Connect to the RPC
            client.Initialize();

            //Set the rich presence
            client.SetPresence(new RichPresence()
            {
                Details = "csharp example",
                State = "csharp example",
                Assets = new Assets()
                {
                    LargeImageKey = "removed",
                    LargeImageText = "removed",
                    SmallImageKey = ""
                }
            });
            Console.ReadLine();
        }
    }`
i dont have any idea what the problem is

Kind regards,
Phil

**Comment by Hampusm** [comment]
Did you forget to import the [dll](
https://github.com/Lachee/discord-rpc-csharp/tree/master/Discord%20RPC)?

**Comment by DopeDealers** [comment]
I did not forget to import it,
Thats why i was so confused

**Comment by Hampusm** [comment]
Can you send output of when you try to compile it?

**Comment by Hampusm** [comment]
**So basically. Discordrpc.dll cant find the PDB file. **

A PDB file is generated by the compiler and contains debugging information. [(Source)](
https://en.m.wikipedia.org/wiki/Program_database)

It looks for a PDB file But cant find one.

It might be a problem with the compiler you use or the dll. 

**Possible fixes:**
• Recompile the DiscordRPC dll
• Delete the PDB file. The compiler should make a new one
If none of the above works:
• Use another compiler

**Comment by DopeDealers** [comment]
hmm, question. when compiling do i throw the PDB file into my projects debug bin/ where it builds
or am i getting that wrong

**Comment by Hampusm** [comment]
Dont do anything to the PDB just let it be and follow the instructions on my previous reply

**Comment by DopeDealers** [comment]
Yes the PDB Generates, but im using a seperate project with the DLL and it gives me that error,
sorry if i sound kind of like a dunce.

**Comment by Hampusm** [comment]
Please send the contents of the PDB then

**Comment by DopeDealers** [comment]
May i just send you the PDB as i cant open it as of now

**Comment by Hampusm** [comment]
Ok

**Comment by DopeDealers** [comment]
[PDB-DLL.zip](https://github.com/Lachee/discord-rpc-csharp/files/2302002/PDB-DLL.zip)
ive also included the drpc dll just incase

**Comment by Hampusm** [comment]
Ok. Sorry But you have to Wait like 4 hours. Im at school

**Comment by DopeDealers** [comment]
yeah thats fine, thank you for helping me

**Comment by Hampusm** [comment]
Nvm i managed to do it now. Did you compile the dll from the native discord Rpc library?

**Comment by DopeDealers** [comment]
no i only used the build script

**Comment by Hampusm** [comment]
From where?

**Comment by DopeDealers** [comment]
https://gyazo.com/a90c2cdffff10d138334c28ae2127453

Im assuming from native rpc library you mean discordapps rpc lib?

**Comment by Hampusm** [comment]
Try to compile the dll with visual studio. Not with the build script. And do not use the native one

**Comment by DopeDealers** [comment]
alright, ill update you once i compile

**Comment by Hampusm** [comment]
[this](
https://github.com/Lachee/discord-rpc-csharp/tree/master/DiscordRPC.Native) is the native Discord RPC library. Do Not use it

**Comment by DopeDealers** [comment]
Ok, compiling from VS seems to have fixed the PDB issue but now alot of my other libs i used that didnt come with a PDB and worked before without it arent working,

Thats not your end tho so ill go ahead and close this. thank you for helping me

**Comment by Hampusm** [comment]
I would be glad to help you further :) What libraries arent working?

**Comment by DopeDealers** [comment]
It seems it was a common problem with the libs i used,
BUT i ran the app i compiled and its still only showing up as an un-rpc
application

[here](https://gyazo.com/52aefd4b51a660eab3dc545059149c9a)

**Comment by DopeDealers** [comment]
I have one more question just so i dont have to open any more issues etc,

this ones not that important so i dont mind waiting awhile
thanks again for earlier

**Comment by Hampusm** [comment]
whats the question?

**Comment by DopeDealers** [comment]
Sorry for the very late reply, but
If i set the RPC inside of the init class etc.

How would i set the details of the RPC and state 
when a user clicks a button

this is the new rpc thing im using

`private static RichPresence presence = new RichPresence()
        {
            Details = "",
            State = "",
            Assets = new Assets()
            {
                LargeImageKey = "icon",
                LargeImageText = "temp",
                SmallImageKey = "temp",
                SmallImageText = "temp"
            }
        };`
