### ISSUE TITLE
Changing status from "Playing [name]" to "Listening to [name]"

### ISSUE THREAD

**Issue by rollersteaam** [Lachee/discord-rpc-csharp#41]
It feels like I've seen people's bots do this before, but I believe the majority of them are written in Python. I might be being stupid here and missing something, but is there a way we can do something like this? I apologize if this question has been asked before, couldn't find it when I tried.

Spotify's real presence is also an example of doing this, albeit they also have a custom UI for their real presence, but I'm assuming that's just a result of their agreement with Discord.

**Comment by Lachee** [comment]
There is no way to do this with Rich Presence, only standard presence set by the gateway (which this library does not handle). You are correct in saying that Spotify does have it, but using a custom system Discord has made for them specifically and isnt open to the public use.

**Comment by rollersteaam** [comment]
Ah okay, thank you for replying. When you say standard presence, is this some kind of way about changing the state of someone's Discord session? This is interesting terminology I haven't heard before, I'm curious on what the difference between real and standard might be.

Do you think if I wanted to change the ""Real Presence's" 'status'" I would need to make some HTTP requests to Discord to make that happen? And would you ever consider trying to do something like this or would it be out of the scope of just sticking to Real Presence? Oh and thanks for your library, it's super easy to use :)

**Comment by rollersteaam** [comment]
Thanks for the additional info, this is going to be useful if I want to attempt to 'extend' my functionality at some point if it seems worth it. Thank you for your time, I guess I'll close this for now
