### ISSUE TITLE
Cant build because .csproj does not know outputPath

### ISSUE THREAD

**Issue by Zhomb** [Lachee/discord-rpc-csharp#43]
Whenever trying to build the solution I get an error about how the output path is not available or not referenced

**Comment by Hampusm** [comment]
What compiler do you use? The compiler might be causing your problem

**Comment by Zhomb** [comment]
I just use the regular Visual Studio Compiler, so I'm not sure why its giving problems since it says to use it in the readme

**Comment by Lachee** [comment]
Can you give the full error please? Its a bit hard to know which of the 3 output paths are not available. There is a potential that one of the outputs are still using absolute path for some reason.

**Comment by Zhomb** [comment]
The OutputPath property is not set for project 'DiscordRPC.csproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='AnyCPU'.  This error may also appear if some other project is trying to follow a project-to-project reference to this project, this project has been unloaded or is not included in the solution, and the referencing project does not build using the same or an equivalent Configuration or Platform.	DiscordRPC			
Here you go, although I tried fixing the csproj it constantly exited after trying to build

**Comment by Hampusm** [comment]
The place were it will output doesn’t exist maybe?

**Comment by Zhomb** [comment]
It did exist, Anyways I fixed it through using visual studio 2015, for some reason 2017 community wont compile the program, even when the directory existed. I'll close this issue for now, but hopefully 2017 will work for it eventually.

**Comment by Hampusm** [comment]
@Zhomb But it works for me and I use Vs2017

**Comment by Zhomb** [comment]
Im not sure what it was then, But after i used 2015 it finally built successfully.
