### ISSUE TITLE
Pipe EndRead being called multiple times possibly.

### ISSUE THREAD

**Issue by HeyItsMeNobody** [Lachee/discord-rpc-csharp#47]
I don't know if this is the correct way to post this but i got this error and have no idea how to fix it.

> System.ArgumentException: 'Either the IAsyncResult object did not come from the corresponding async method on this type, or EndRead was called multiple times with the same IAsyncResult.'

What i am doing is:
`        public static DiscordRpcClient customRPClient = null;

        public static void SetCustomRPC(string details, string state)
        {
            customRPClient = new DiscordRpcClient("506120925280993305");
            customRPClient.Initialize();

            customRPClient.SetPresence(new RichPresence()
            {
                Details = details,
                State = state,
            });
        }`
Then calling it from a other class..

**Comment by Hampusm** [comment]
> Then calling it from a other class..
Is problably the problem. It expects the result to come from the same class

**Comment by Lachee** [comment]
Yeah this seems like a bug in the library. Have you made sure you are using the latest version of the DLL?
This library should be threadsafe as it runs everything in a new thread. So where you call it shouldnt matter, as long as you are not creating multiple clients to the same pipe (which may cause conflicts).

**Comment by HeyItsMeNobody** [comment]
Yep, It is the latest version and even if i try the example it outputs the same thing.

**Comment by HeyItsMeNobody** [comment]
I believe it is the latest version, Not so sure though.. but if i try the example it outputs the same thing.

**Comment by Lachee** [comment]
Author never came back and bug cannot be reproduced.
