### ISSUE TITLE
Change primary name

### ISSUE THREAD

**Issue by joelpraxedes** [Lachee/discord-rpc-csharp#48]
Hello, so I'm programming in C #, I was interested in showing information in discord but did not know where to start. Then I found the files you published, everything worked, but I would like to know where I change the name that appears in the discord. "DISCORD APC .NET" - I searched the code and did not find ...

* Remember, I do not know if it's a problem. Sorry if I posted in the wrong place for that matter.

Congratulations and I await your response!

**Comment by Lachee** [comment]
Hello, what you want to do is make a new Discord Application on the developer portal. You can do so here:
https://discordapp.com/developers/applications/

Once you create your application (the name of the application will be what is shown), copy the Client ID and paste it in the constructor of the DiscordRpcClient.

Then you want to upload custom assets and images you can use, do so by going to the Rich Presence tab, then Art Assets.
