### ISSUE TITLE
No parties/join request stuff/etc

### ISSUE THREAD

**Issue by Agrair** [Lachee/discord-rpc-csharp#55]
I attempted to use this library without creating parties, subscriptions, or anything that involves actual interaction in discord (basically, I set up a client that updates Details and State, nothing else). However, nothing happened. Is there a way to get around it? I don’t want “Join” and “Specate” buttons, etc.

**Comment by Lachee** [comment]
They are not required, are you sure you have setup the client correctly? Its not a "use then dispose" client, it has to say alive for the lifetime of your app. Can you share the code you used to implement it?

**Comment by Agrair** [comment]
https://raw.githubusercontent.com/Dradonhunter11/TerrariaUltraApocalypse/testBranch/DRPSystem.cs?token=Aoeo-kJdWoSd31ncTCvl5ObbhWZqaASaks5cjccLwA%3D%3D This is part of a private repository, not sure if you can see it.

**Comment by Agrair** [comment]
Also, if I didn’t make myself clear, I just don’t want parties (the “(5 of 10)” thing) and the Join and Spectate things.

**Comment by Lachee** [comment]
Join and Spectate buttons are visible if you assign a Join / Spectate Secret. The (5 of 10) is the party and appears if you give a Party object to the RP. Subscriptions are events from the buttons. You must subscribe to the events of the Join / Spectate in order to get them and that is what the subscription does. 

I can see your code and it looks all good. Maybe try setting the presence on the OnRead event instead like: 
```cs
 client.OnReady += (sender, args) => 
{ 
    Logger.Info("Rich Presence is ready for connection!"); 
    client.SetPresence(presence);
};
```

Everything should work otherwise. Can you give me more logs from the client? Give the DiscordRpcClient a logger (like the file logger) and set the level to Trace:
```cs
client = new DiscordRpcClient(ClientID, SteamID64Checker.CurrentSteamID64, true, -1, new Logging.FileLogger() { Level = DiscordLogLevel });
```

**Comment by Agrair** [comment]
Due to various other reasons, I am currently unable to compile it in the context above. However, I do have this: https://pastebin.com/BiQM9YRB, and the log (which is absolutely massive): https://pastebin.com/Xexxmdyi

**Comment by Agrair** [comment]
I don't think it's reaching it's "Ready" stage for some reason, but I can't make out anything from the log.

**Comment by Lachee** [comment]
```
ERR : Unhandled Exception: System.IO.FileNotFoundException
ERR : Could not load file or assembly 'Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
```
You need Newtonsoft.Json. Its a dependency.

**Comment by Agrair** [comment]
K, I’ll have to find that somewhere in my nuget folder.

**Comment by Agrair** [comment]
Hmmm, looks like one of my collabs fixed it, but thanks for your help, and thanks for making this library in the first place.
