### ISSUE TITLE
client.onready never executing

### ISSUE THREAD

**Issue by doteq** [Lachee/discord-rpc-csharp#57]
I used example code, (winform, visual c# .net 3.5). Rpc showing but. Client.onready does not executing

**Comment by Hampusm** [comment]
Have you installed newtonsoft.json?

**Comment by Lachee** [comment]
Are you invoking the `client.Invoke()` method regularly?

**Comment by doteq** [comment]
I have installed newtonsoft.json but I forgot about ```client.Invoke()``` I'll chetk that's later. Thanks!
