### ISSUE TITLE
User tostring issue

### ISSUE THREAD

**Issue by OfficerX** [Lachee/discord-rpc-csharp#58]
Hey, you should replace this: https://github.com/Lachee/discord-rpc-csharp/blob/351ae348756db3c879bde8070f9919ffd76cf5c2/DiscordRPC/User.cs#L149

with this:

`return Username + "#" + Discriminator.ToString("D4");`

**Comment by Lachee** [comment]
Thanks a ton, total oversight. This has been fixed now :)
