### ISSUE TITLE
Doesn't connect.

### ISSUE THREAD

**Issue by HelloKitty3000** [Lachee/discord-rpc-csharp#60]
Hey, this is my first day experimenting with this library.. I've messed around with my code multiple ways and It keeps failing to connect or I really don't know what's going on, they're no errors or anything showing me what the problem is.

Here is my code
`
https://hastebin.com/ulexifutuq.cs
`

Thanks :D

**Comment by Lachee** [comment]
Can you set the logger to trace and give me the log?

**Comment by HelloKitty3000** [comment]
> Can you set the logger to trace and give me the log?

I switched too console application and it worked, so I guess closed?

**Comment by Lachee** [comment]
I guess so? either way it should work on non-console applications. 
Closed the issue anyways because you have it working.
