### ISSUE TITLE
Found conflicts between different versions of "Newtonsoft.Json"

### ISSUE THREAD

**Issue by cxnky** [Lachee/discord-rpc-csharp#63]
I'm using Newtonsoft v1.11 in my project, installed via NuGet, when I build I get the warning: 

``Found conflicts between different versions of "Newtonsoft.Json that could not be resolved"``
When I build, the RPC client then says that it cannot find v1.11 of Newtonsoft.Json even though I have the DLL in the same directory as my program

**Comment by Lachee** [comment]
The nuget has recently upgraded to v1.12.1. Try updating the package and see if that solves the problem :)

**Comment by Lachee** [comment]
Closed because of age.
