### ISSUE TITLE
.NET Core Support?

### ISSUE THREAD

**Issue by mat1jaczyyy** [Lachee/discord-rpc-csharp#65]
I would like to add Discord Rich Presence to my application which targets Windows and macOS via netcoreapp2.2. Does this project support .NET Core for cross-platform? If not, are there plans to bring support?

**Comment by Lachee** [comment]
While it is not a .net core library, you can use it still in your .net core applications. I have used it myself in a .net core app without any issues. This library already has cross-platform support too, although MacOS will still need some further testing and possible bug fixing. 

I do have plans to create a .net core branch of this project, but it wont be main release until I am convinced nobody is using .NET 3.5 anymore for their Unity projects. I am also quite busy IRL so I cannot dedicated as much time into the branch either.

If you have any issues running this library in your .net core application, feel free to create a new issue and I will try to resolve :+1: For the most part, "it should just work".

**Comment by mat1jaczyyy** [comment]
I see, thanks for your quick response. I will attempt to integrate the NuGet library first because I would like to avoid keeping rpc source code in my repo.

**Comment by mat1jaczyyy** [comment]
NuGet library working perfectly on both macOS and Windows!
