### ISSUE TITLE
Query about DotNetCore Compatibility

### ISSUE THREAD

**Issue by roberestarkk** [Lachee/discord-rpc-csharp#66]
Tried to send an email but couldn't find any working contact methods.

Just wondering what level of Core compatibility there is with this project.
There are specific instructions for targeting Core, but when doing a `dotnet restore` it warns that it restores with target .NETFramework instead of .NETCoreApp.

Is it compatible in the sense that you can use it from Core as long as you've also got Framework, or is it truly compatible (can run on Linux/Mac just fine) and it just restored to Framework because reasons?

**Comment by Lachee** [comment]
Well, it is a .net framework library. While fx libraries are not truly compatible with core, I have personally had no troubles using the library in a dotnet environment on Linux other than some minor snap sandboxing (which has since been fixed).

**Comment by roberestarkk** [comment]
Ah excellent! Thank you :)
This is so much simpler than the WebSocket client, and we get Rich Presence on top!
