### ISSUE TITLE
Adding events on runtime

### ISSUE THREAD

**Issue by reithegoat** [Lachee/discord-rpc-csharp#67]
Just a question. Am I able to add events to the Discord client events during runtime? Or forced to add the events via the editor. Here are some code to get an idea.
```
Discord.client.OnJoin += Client_OnJoin;
Discord.client.OnJoinRequested += Client_OnJoinRequested;
```

**Comment by Lachee** [comment]
You can add events at runtime. If you are using just the RPC library, its exactly as you have done it, but if you are using the DiscordManager in the unity package, you will want to the [Add Listener](https://docs.unity3d.com/ScriptReference/Events.UnityEvent.AddListener.html) from the UnityEvent class.
