### ISSUE TITLE
Update text

### ISSUE THREAD

**Issue by Nekiplay** [Lachee/discord-rpc-csharp#79]
My code looks something like this

> private async void update()
        {
            /*
            Create a discord client
            NOTE: 	If you are using Unity3D, you must use the full constructor and define
                     the pipe connection.
            */
            client = new DiscordRpcClient("appid");
            //Subscribe to events
            client.OnReady += (sender, e) =>
            {
                Console.WriteLine("Received Ready from user {0}", e.User.Username);
            };
            client.OnPresenceUpdate += (sender, e) =>
            {
                Console.WriteLine("Received Update! {0}", e.Presence);
            };
            //Connect to the RPC
            client.Initialize();
            //Set the rich presence
            //Call this as many times as you want and anywhere in your code.
            client.SetPresence(new RichPresence()
            {
                Details = "Онлайн: " + textBox1.Text,
                State = "Staff онлайн: " + textBox19.Text,
                Assets = new Assets()
                {
                    LargeImageKey = "12",
                    LargeImageText = "mc.megacraft.org",
                    SmallImageKey = "image_small"
                }
            });
        }

**Comment by Lachee** [comment]
Thats some nice looking code, but you havn't stated your actual issue.

**Comment by Lachee** [comment]
Closed as it has been 24 Days without any further comments.
