### ISSUE TITLE
Presence StartTime starting at 7h

### ISSUE THREAD

**Issue by MechaDragonX** [Lachee/discord-rpc-csharp#85]
*I also have this issue on my own repo [here](https://github.com/MechaDragonX/Chilong/issues/2).*

In my code I start the presence with this:
```cs
client.SetPresence(new RichPresence
{
	// "sumatra" is a Process
	Details = sumatra.MainWindowTitle.TrimEnd(" - SumatraPDF".ToCharArray()),
	State = "State Placeholder",
	Timestamps = new Timestamps(DateTime.Now)
});
```

I expected the time to start at 00:01, but it instead looks like this:
![24/03/2020 Screenshot](https://bit.ly/39jnhoi "24/03/2020 Screenshot")

**Comment by Lachee** [comment]
That is because you are 7 hours ahead. You should use `DateTime.UtcNow`.

**Comment by MechaDragonX** [comment]
Oh ok! Thanks!
