### ISSUE TITLE
[Addition] Show Cover Art

### ISSUE THREAD

**Issue by youkknowho** [Lachee/discord-rpc-csharp#87]
Anyway you can get the dll to read the Comment Metadata from songs to display the cover art\
because I usually tag the song's comment with the art url, maybe that can help display it in rich presence, I know the soundcloud rp (https://github.com/demaisj/soundcloud-rp) uses this in a similar way
![image](https://user-images.githubusercontent.com/45168911/82054845-2974e480-96f2-11ea-982d-7e380a68238b.png)

**Comment by Lachee** [comment]
Discord doesn't expose the API to upload images, and thus this library will not include it to keep the paradigm "if its not documented, dont use it".
