### ISSUE TITLE
ApplicationId change on fly?

### ISSUE THREAD

**Issue by PurplefinNeptuna** [Lachee/discord-rpc-csharp#88]
Is there any way to change `application_id` on fly?
For now, I change application id by recreating `DiscordRpcClient` every time I want to change the id.
And it took some time from old rich presence to the new one to show (i can see normal game status between changes)

**Comment by Lachee** [comment]
No, the application_id is sent as part of the initialisation and handshake with discord. A new connection is required for a new application id.
