### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Agent-Mimos** [Lachee/discord-rpc-csharp#90]
When I Close The App And Reopen It. It doesn't work what do i need to do

**Comment by Agent-Mimos** [comment]
And a lot of latency

**Comment by M1XT3NZ** [comment]
What exactly do you mean with
"doesnt work"
not really an explanation on what doesnt work.

**Comment by Lachee** [comment]
You have gone out of your way to ignore the Bug report formatting. Please use the appropriate template when reporting bugs.
