### ISSUE TITLE
How would I do RPC types like watching etc.

### ISSUE THREAD

**Issue by JunctionNinja** [Lachee/discord-rpc-csharp#98]
Just wondering...

**Comment by Lachee** [comment]
They are not RPC types, they are activity types. There is a distinction between Activity and Rich Presence.
The activity (or status) is what is displayed in discord. It can be either Playing, Watching, Listening, Streaming. 
RPC (or actually just Rich Presence) is just the metadata associated with the `Playing` type.

tl;dr
this library cannot set it to anything but playing as that is a limitation on discord's end.
